### ISSUE TITLE
Run as Subdirectory instead of Custom domain

### ISSUE THREAD

**Issue by TheMardy** [BoolCode/appwrite-funcover#5]
Hi,
Is it possible to run Funcover as Subdirectory instead of Custom domain?
I tried to set it up with `PathPrefix('/v1/webhook')` instead of `Host('custom.domain.com') && PathPrefix('/')` but I couldn't get that to work.
It would make things easier with certificates, as I think that certificates will not be automatically renewed the way things are set up at the moment.
Thanks for creating Funcover :)

**Comment by byawitz** [comment]
Thank you 😄 

That's a great idea.
Let me run some checks.

**Comment by byawitz** [comment]
Feature as added, Thanks again for your suggestion!

**Comment by byawitz** [comment]
Feature as added, Thanks again for your suggestion!
