### ISSUE TITLE
Access the raw request body to process Stripe webhook

### ISSUE THREAD

**Issue by davevanhoorn** [BoolCode/appwrite-funcover#9]
I'm back Binyamin, sorry 😅

Is there a way to access the raw body text while also using `FLATTEN_HEADERS=true`?

Asking this because I'd like to implement Stripe's constructEvent function to verify that a webhook that Funcover enables is actually triggered by Stripe.

To validate a triggered webhook, Stripe's `constructEvent` needs the requests raw body text:

```
/**
 * Raw text body payload received from Stripe.
 */
payload: string | Buffer,
```

In your documentation I read the following: `Also, You can use a filed named rawData to pass data directly to data key. Here's an example in JSON`, but it's not completely clear what to do or how to implement it, as I can't control what Stripe sends.

Could you point me in the right direction? Or is this something that Funcover hasn't implemented?

Thanks, Dave

**Comment by byawitz** [comment]
Hey Dave.
The opposite, thanks for opening this issue.

Are you referring to Strip fulfillment logic?
Then you can do something like so when `FLATTEN_HEADERS=true`
```js
// First, Get the payload.
const payload = JSON.parse(req.payload);

// Second, parse the data and the headers.
const data    = JSON.parse(payload.data);
const headers = JSON.parse(payload.headers);

const form = $.param(data) // convert JSON to formData using any method, an example using jQuery.
await stripe.webhooks.constructEventAsync(form, headers["stripe-signature"], YOUR_STRIP_SECRET);
```

As for this part
> Also, You can use a field named rawData to pass data directly to data key. Here's an example in JSON

You're correct and this is meant only for when you're controlling the POST request, otherwise, you should use the above logic.

**Comment by davevanhoorn** [comment]
Thanks Binyamin,

I've tried the following:

1. Convert the payload data to `FormData`.
2. Double checked if the `FormData` contains the data from the request.
3. Pass the converted FormData to Stripe's `constructEventAsync`, which accepts a `string` or `Buffer`, so I added `as unknown as string` to "fix" the TypeScript error.
4. The try/catch statement fails with the following error: `Webhook payload must be provided as a string or a Buffer (https://nodejs.org/api/buffer.html) instance representing the _raw_ request body. Payload was provided as a parsed JavaScript object instead.`

Any hints where to go from here? I guess Funcover parses it, then I create the FormData in the serverless function, but Stripe knows it's not the raw request?

**Comment by davevanhoorn** [comment]
I was overthinking it. Below code works:

```
const payload = JSON.parse(req.payload);
const data = JSON.parse(payload.data);
const headers = JSON.parse(payload.headers);

const webhookSignature = headers['stripe-signature'];
const webhookSecret = WEBHOOK_STRIPE_CONNECT_SECRET;

const stripe = new Stripe(STRIPE_SECRET_KEY);

try {
  stripe.webhooks.constructEventAsync(
    payload.data, // <-- payload.data, hasn't been parsed with JSON.stringify()
    webhookSignature,
    webhookSecret
  );
  console.log('Stripe webhook secret and signature verified');
} catch (err) {
  console.log('Stripe webhook secret and signature not verified');
  console.log(err);
}
```

Thanks again Binyamin! 😀

**Comment by davevanhoorn** [comment]
Scratch my previous answer. It unfortunately doesn't work as I expected. The message I get from the Stripe function is:

`No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe?`

Looking at this issue: https://github.com/stripe/stripe-node/issues/1254#issuecomment-957945805, it seems they had a similar challenge but found a workaround.

Is there a way to access the raw body in the Appwrite function, without converting it to FormData?

Edit: maybe it's an option to use Hono's `c.req.raw` ([see documentation](https://hono.dev/api/request#raw)) to add the raw request body and allow it to be used in the Appwrite function. Similar to what you've done with the headers.

E.g.

```
if (process.env.FLATTEN_HEADERS === 'true') {
        return {
            data: JSON.stringify({
                data: data.data,
                headers: JSON.stringify(c.req.headers.toJSON()),
                rawBody: JSON.stringify(c.req.raw.body.toJSON()) <--- not sure if this can even work
            })
        }
    }
```

Not sure if that's a dumb suggestion with serializing etc, but it's the first thing that comes to mind.

**Comment by byawitz** [comment]
That sounds like a good suggestion. 

Today Appwrite is going to release [version 1.4](https://twitter.com/appwrite/status/1696845162637398496)
From what I know it should solve the whole need of Funcover altogether.

If it won't solve that matter I'll upload a new version of Funcover.

Thanks 👍

**Comment by davevanhoorn** [comment]
Thanks for the heads up Binyamin. I'll look into 1.4!
